name: Dependencies and test CI pipeline

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


        #Install Python  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r project/requirements.txt

      - name: Create .env file from secrets
        run: |
            echo "TEM_DAT_USERNAME=${{ secrets.EM_DAT_USERNAME }}" >> project/components/.env
            echo "TEM_DAT_PASSWORD=${{ secrets.EM_DAT_PASSWORD }}" >> project/components/.env

      - name: Make tests.sh executable
        run: chmod +x project/tests.sh

      - name: Run tests
        run: project/tests.sh


