name: Dependencies and test CI pipeline

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 126
          install-chromedriver: true
      
      - name: Check Chrome Version        
        run: chrome --version 
  
#      - name: Set up ChromeDriver
#        uses: nanasess/setup-chromedriver@v2.2.2
         
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create .env file from secrets
        run: |
            echo "EM_DAT_USERNAME=${{ secrets.EM_DAT_USERNAME }}" >> project/components/.env
            echo "EM_DAT_PASSWORD=${{ secrets.EM_DAT_PASSWORD }}" >> project/components/.env

      - name: Set up temporary directory
        run: mkdir -p temp
    
      - name: Set environment variable for temp directory
        run: echo "DOWNLOAD_DIR=$GITHUB_WORKSPACE/temp" >> $GITHUB_ENV

      - name: Make tests.sh executable
        run: chmod +x project/tests.sh

      - name: Run tests
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99.0
          nohup Xvfb :99 -screen 0 1024x768x16 &
          project/tests.sh



